M = {}

M.default_colors = {
    darkBlue = "#004c73",
    darkCyan = "#007373",
    darkGreen = "#005523",
    darkGrey1 = "#07080d",
    darkGrey2 = "#14161b",
    darkGrey3 = "#2c2e33",
    darkGrey4 = "#4f5258",
    darkMagenta = "#470045",
    darkRed = "#590008",
    darkYellow = "#6b5300",
    lightBlue = "#a6dbff",
    lightCyan = "#8cf8f7",
    lightGreen = "#b3f6c0",
    lightGrey1 = "#eef1f8",
    lightGrey2 = "#e0e2ea",
    lightGrey3 = "#c4c6cd",
    lightGrey4 = "#9b9ea4",
    lightMagenta = "#ffcaff",
    lightRed = "#ffc0b9",
    lightYellow = "#fce094",
}

function M.get_float_opts()
    -- vim.cmd([[autocmd! ColorScheme * highlight NormalFloat guibg=#1f2335]])
    -- vim.cmd([[autocmd! ColorScheme * highlight FloatBorder guifg=white guibg=#1f2335]])

    -- local border = {
    --     { "🭽", "FloatBorder" },
    --     { "▔", "FloatBorder" },
    --     { "🭾", "FloatBorder" },
    --     { "▕", "FloatBorder" },
    --     { "🭿", "FloatBorder" },
    --     { "▁", "FloatBorder" },
    --     { "🭼", "FloatBorder" },
    --     { "▏", "FloatBorder" },
    -- }

    -- local winhighlight = "NormalFloat:NormalFloat,FloatBorder:FloatBorder,CursorLine:Visual,Search:None"

    local winblend = 0

    -- return { border = border, winhighlight = winhighlight, winblend = winblend }
    return { winblend = winblend }
end

M.icons = {
    misc = {
        dots = "󰇘",
    },
    dap = {
        Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
        Breakpoint = { " ", "DapUIStop" },
        -- Breakpoint = { " ", "DapUIStop" },
        BreakpointCondition = " ",
        BreakpointRejected = { " ", "DiagnosticError" },
        LogPoint = ".>",
    },
    diagnostics = {
        Error = " ",
        Warn = " ",
        Hint = " ",
        Info = " ",
        BoldError = "",
        BoldWarning = "",
        Warning = "",
        BoldInformation = "",
        Information = "",
        BoldQuestion = "",
        Question = "",
        BoldHint = "",
        Debug = "",
        Trace = "✎",
    },
    git = {
        added = " ",
        modified = " ",
        removed = " ",
        LineAdded = "",
        LineModified = "",
        LineRemoved = "",
        FileDeleted = "",
        FileIgnored = "◌",
        FileRenamed = "",
        FileStaged = "S",
        FileUnmerged = "",
        FileUnstaged = "",
        FileUntracked = "U",
        Diff = "",
        Repo = "",
        Octoface = "",
        Branch = "",
    },
    kinds = {
        Array = " ",
        Boolean = "󰨙 ",
        Class = " ",
        Codeium = "󰘦 ",
        Color = " ",
        Control = " ",
        Collapsed = " ",
        Constant = "󰏿 ",
        Constructor = " ",
        -- Copilot = " ",
        Copilot = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = " ",
        Function = "󰊕 ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = "󰊕 ",
        Module = " ",
        Namespace = "󰦮 ",
        Null = " ",
        Number = "󰎠 ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = "󰆼 ",
        TabNine = "󰏚 ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = "󰀫 ",
    },
    ui = {
        ArrowCircleDown = "",
        ArrowCircleLeft = "",
        ArrowCircleRight = "",
        ArrowCircleUp = "",
        BoldArrowDown = "",
        BoldArrowLeft = "",
        BoldArrowRight = "",
        BoldArrowUp = "",
        BoldClose = "",
        BoldDividerLeft = "",
        BoldDividerRight = "",
        BoldLineLeft = "▎",
        BookMark = "",
        BoxChecked = "",
        Bug = "",
        Stacks = "",
        Scopes = "",
        Watches = "󰂥",
        DebugConsole = "",
        Calendar = "",
        Check = "",
        ChevronRight = "",
        ChevronShortDown = "",
        ChevronShortLeft = "",
        ChevronShortRight = "",
        ChevronShortUp = "",
        Circle = " ",
        Close = "󰅖",
        CloudDownload = "",
        Code = "",
        Comment = "",
        Dashboard = "",
        DividerLeft = "",
        DividerRight = "",
        DoubleChevronRight = "»",
        Ellipsis = "",
        EmptyFolder = "",
        EmptyFolderOpen = "",
        File = "",
        FileSymlink = "",
        Files = "",
        FindFile = "󰈞",
        FindText = "󰊄",
        Fire = "",
        Folder = "󰉋",
        FolderOpen = "",
        FolderSymlink = "",
        Forward = "",
        Gear = "",
        History = "",
        Lightbulb = "",
        LineLeft = "▏",
        LineMiddle = "│",
        List = "",
        Lock = "",
        NewFile = "",
        Note = "",
        Package = "",
        Pencil = "󰏫",
        Plus = "",
        Project = "",
        Search = "",
        SignIn = "",
        SignOut = "",
        Tab = "󰌒",
        Table = "",
        Target = "󰀘",
        Telescope = "",
        Text = "",
        Tree = "",
        Triangle = "󰐊",
        TriangleShortArrowDown = "",
        TriangleShortArrowLeft = "",
        TriangleShortArrowRight = "",
        TriangleShortArrowUp = "",
    },
    logos = {
        arch = "󰣇",
        nixos = "",
        neovim = "",
    },
}

return M
